permissions:
    pages: write
    id-token: write
    contents: read

name: Deploy Blazor WebAssembly to GitHub Pages

on:
    push:
        branches:
            - main # or master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x" # or 7.0.x depending on your project

            - name: Publish Blazor WebAssembly app
              run: dotnet publish -c Release -o release

            - name: Add .nojekyll file
              run: touch release/wwwroot/.nojekyll

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: release/wwwroot
